import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Doctor App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.className} min-h-screen flex flex-col  px-4`}>
        <Navbar />

        <main className="flex-1 container mx-auto">
          {children}
          <Toaster />
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}